### PR TITLE
HeaderLine Verifier

### PR DESCRIPTION
**Pull request by labm1997**
Added methods that verify if headerline of a request or response is valid
Fixed regexp to allow host with 'http://...' on spider

### CODE REVIEW

**Review by AndreLaranjeira — COMMENTED** [review]
This code is what I need to finish my feature and seems really well designed.
I just have some questions:
1) Shouldn't the validAnswerHL and validRequestHL return the 'and' value of both method call returns instead of the 'or' value? Because if one of those fails, then the entire method should fail, no?
2) Instead of using `if(!condition) { return false; }` why no just use `return condition` in the parseCL methods and alike?

**Comment by AndreLaranjeira** [comment]
Since I'm working on this right now, I'll make the aforementioned changes and save them in a commit in my branch. If they were wrong, I'll just revert the commit.

**Comment by labm1997** [comment]
Answers to questions:
1. It's 'or' because line can be ether command or header. If fail command, try header, if fail header too than it's not valid. The condition x || y is equivalent to !(!x && !y) which means return false if both x and y are not true.
2. True, in fact for `parseAL` and `parseCL` it's ambiguous, but not for `parseHL` that performs some operations before returning. As I coded  parseHL` before, the others inherited a similar structure.

**Comment by AndreLaranjeira** [comment]
I cherry-picked and modified this commit into my PR, therefore this PR is now stale.

**Pull request closed without merging**
